def get_patterns():
    """JavaScript-specific vulnerability patterns."""
    return {
        "sql_injection": [
            r'execute\s*\(\s*["\'][^"\']*\$\{',
            r'query\s*\(\s*["\'][^"\']*\$\{',
            r'db\.query\s*\(',
            r'sequelize\.',
            r'knex\.',
            r'connection\.query\s*\(',
            r'pool\.query\s*\(',
            r'mysql\.',
            r'sqlite\.',
            r'mongoose\.',
            r'mongodb\.'
        ],
        "command_injection": [
            r'eval\s*\(',
            r'setTimeout\s*\(\s*["\']',
            r'setInterval\s*\(\s*["\']',
            r'Function\s*\(',
            r'new\s+Function\s*\(',
            r'child_process',
            r'spawn\s*\(',
            r'exec\s*\(',
            r'execFile\s*\(',
            r'fork\s*\(',
            r'process\.',
            r'require\s*\([\'"]child_process[\'"]'
        ],
        "xss": [
            r'innerHTML\s*=',
            r'outerHTML\s*=',
            r'document\.write\s*\(',
            r'\.html\s*\(',
            r'dangerouslySetInnerHTML',
            r'insertAdjacentHTML\s*\(',
            r'\.append\s*\(',
            r'\.prepend\s*\(',
            r'\.after\s*\(',
            r'\.before\s*\(',
            r'\.replaceWith\s*\(',
            r'createContextualFragment\s*\(',
            r'location\.href\s*=',
            r'location\.replace\s*\(',
            r'location\.assign\s*\(',
            r'\.src\s*=',
            r'\.srcdoc\s*='
        ],
        "insecure_deserialization": [
            r'JSON\.parse\s*\(',
            r'deserialize\s*\(',
            r'unserialize\s*\(',
            r'fromJSON\s*\(',
            r'parseJSON\s*\(',
            r'eval\s*\(\s*["\'][^"\']*JSON',
            r'\.deserializeObject\s*\(',
            r'\.fromString\s*\('
        ],
        "path_traversal": [
            r'fs\.',
            r'require\s*\([\'"]fs[\'"]',
            r'readFile\s*\(',
            r'writeFile\s*\(',
            r'readFileSync\s*\(',
            r'writeFileSync\s*\(',
            r'createReadStream\s*\(',
            r'createWriteStream\s*\(',
            r'read\s*\(',
            r'write\s*\(',
            r'path\.join\s*\(',
            r'path\.resolve\s*\(',
            r'__dirname',
            r'__filename'
        ],
        "prototype_pollution": [
            r'Object\.assign\s*\(',
            r'Object\.merge\s*\(',
            r'Object\.extend\s*\(',
            r'jQuery\.extend\s*\(',
            r'deepExtend\s*\(',
            r'deepMerge\s*\(',
            r'lodash\.merge\s*\(',
            r'lodash\.extend\s*\(',
            r'_.merge\s*\(',
            r'_.extend\s*\(',
            r'\$\.extend\s*\(',
            r'Object\.setPrototypeOf\s*\(',
            r'__proto__'
        ],
        "weak_crypto": [
            r'crypto\.createHash\s*\(\s*["\']md5["\']',
            r'crypto\.createHash\s*\(\s*["\']sha1["\']',
            r'createCipher\s*\(',
            r'createDecipher\s*\(',
            r'MD5\s*\(',
            r'SHA1\s*\(',
            r'CryptoJS\.MD5\s*\(',
            r'CryptoJS\.SHA1\s*\(',
            r'CryptoJS\.AES\.encrypt\s*\('
        ],
        "insecure_random": [
            r'Math\.random\s*\(',
            r'new\s+Date\(\)\.getTime\s*\(',
            r'Date\.now\s*\(',
            r'new\s+Date\s*\('
        ],
        "broken_auth": [
            r'==\s*["\']',
            r'["\']\\s*==',
            r'===\s*["\']',
            r'["\']\\s*===',
            r'\.equals\s*\(',
            r'\.equals\s*\(',
            r'\.equalsIgnoreCase\s*\(',
            r'\.toLowerCase\s*\(\s*\)\s*==',
            r'==\s*\.toLowerCase\s*\(\s*\)',
            r'localstorage\.',
            r'sessionstorage\.',
            r'document\.cookie',
            r'\.setItem\s*\(',
            r'\.getItem\s*\('
        ]
    }